package com.projet.models.utils;

public enum EventType {
    GAME_START, GAME_SET_UP, TURN_START, CHOOSE_CARD, CHOOSED_CARD, STOLE_PLAYER, STEAL_PLAYER, STEAL_CARD, STOLE_CARD, TROPHEY_GIVEN, SCORE_GIVEN
}
